version: '3.8'

services:
  web:
    image: ${DOCKER_IMAGE}
    ports:
      - "80:80"
    restart: always
    # 볼륨 마운트 (개발 시 유용)
    # volumes:
    #   - ./dist:/usr/share/nginx/html
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 