version: '3.8'

services:
  web:
    image: ${DOCKER_HUB_USERNAME}/franchise-website:latest
    container_name: franchise-website
    ports:
      - "9876:80"  # 외부:내부 포트
    restart: always
    environment:
      - NODE_ENV=production
      - TZ=Asia/Seoul
    networks:
      - web-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    # 필요한 경우 볼륨 설정
    # volumes:
    #   - ./logs:/var/log/nginx
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  web-network:
    driver: bridge 