services:
  web:
    image: ${DOCKER_IMAGE}
    container_name: franchise-website
    ports:
      - "0.0.0.0:9876:9876" # 외부:내부 포트
    restart: always
    environment:
      - NODE_ENV=production
      - TZ=Asia/Seoul
      - VITE_API_URL=http://franchise-backend:3000 # 백엔드 컨테이너 이름과 포트
    networks:
      - franchise-network
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9876/" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  franchise-network:
    external: true
