services:
  web:
    image: ${DOCKER_HUB_USERNAME}/franchise-website:latest
    container_name: franchise-website
    restart: always
    ports:
      - "0.0.0.0:9876:9876" # 외부:내부 포트
    environment:
      - NODE_ENV=production
      - TZ=Asia/Seoul
    networks:
      - franchise-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9876/ || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 120s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  franchise-network:
    external: true
