apiVersion: v1
kind: Service
metadata:
  name: franchise-website-service
  labels:
    app: franchise-website
spec:
  type: NodePort  # Docker Desktop Kubernetes에서 더 쉽게 접근 가능
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # 30000-32767 범위 내에서 설정
    protocol: TCP
    name: http
  selector:
    app: franchise-website 