name: CI/CD Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Build project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: dist/

  docker-build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/franchise-website:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/franchise-website:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/franchise-website:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/franchise-website:buildcache,mode=max

  deploy:
    needs: docker-build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Copy Kubernetes config and deployment files via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "k8s/,k8s-deploy.sh,.env.example"
          target: "C:/Users/lee/franchise-website"
          strip_components: 0

      - name: Execute remote Kubernetes deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          command_timeout: 30m
          script: |
            cd C:/Users/lee/franchise-website
            {
              echo "=== 배포 시작 시간: $(date) ==="
              echo "=== k8s-deploy.sh 실행 중... ==="
              bash k8s-deploy.sh "${{ secrets.DOCKER_HUB_USERNAME }}" "${{ github.sha }}"
              echo "=== 배포 완료 시간: $(date) ==="
            } 2>&1 | tee deployment.log

      - name: Check deployment log exists
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd C:/Users/lee/franchise-website
            if [ -f deployment.log ]; then
              echo "deployment.log 파일이 존재합니다."
              cat deployment.log
            else
              echo "deployment.log 파일이 생성되지 않았습니다."
              exit 1
            fi

      - name: Download deployment log
        uses: appleboy/scp-action@master
        continue-on-error: true
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "C:/Users/lee/franchise-website/deployment.log"
          target: "."
          strip_components: 0

      - name: Upload deployment log
        uses: actions/upload-artifact@v4
        with:
          name: deployment-log
          path: deployment.log
          if-no-files-found: warn
